// Generated by hand from the committed `android/app/google-services.json` and
// `ios/Runner/GoogleService-Info.plist`. Once the FlutterFire CLI is available,
// regenerate this file with `flutterfire configure` so it also covers web and
// desktop and stays in sync with the Firebase console.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  const DefaultFirebaseOptions._();

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'Firebase is not configured for web in PecoNote. '
        'Run `flutterfire configure` to add it.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'Firebase is only configured for Android and iOS in PecoNote '
          '(got $defaultTargetPlatform).',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0UOVAi5AHll2Z2tTn3wapEfZW5Bb4kQM',
    appId: '1:607901324874:android:29bd637ba612db8851f8b3',
    messagingSenderId: '607901324874',
    projectId: 'peconote-7b134',
    storageBucket: 'peconote-7b134.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZUJ--0ShqchCFoEfq_u9C5GjcHD5wXXE',
    appId: '1:607901324874:ios:eaf610d4a638c2cd51f8b3',
    messagingSenderId: '607901324874',
    projectId: 'peconote-7b134',
    storageBucket: 'peconote-7b134.firebasestorage.app',
    iosBundleId: 'com.example.peconoteMobile',
  );
}
